requires = ['tox>=4']
env_list = ['clean', '3.9', '3.10', '3.11', '3.12', '3.13']

[env_run_base]
description = 'Run tests for the package'
extras = ['test']
commands = [
  ['coverage', 'run', '--source={env_site_packages_dir}/dry_foundation', '-m', 'pytest'],
  ['coverage', { replace = 'posargs', default = ['report'], extend = true }],
]

[env.clean]
deps = ['coverage[toml]']
skip_install = true
commands = [ ['coverage', 'erase'] ]
